accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logout, name='logout'),
]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_chat_list, name='home'),
    path('chat/<int:receiver_id>/', views.chat_detail, name='chat'),
    path('chat/global/', views.global_chat, name='global'),
    path('add-group/', views.add_group, name='add_group'),
    path('chat/group/', views.group_chat, name='group'),
    path('chat/group/<str:chat_room_id>/', views.group_chat, name='group_with_id'),
]

chat_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
]

templates/add_group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Group</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f4f4f4;
            padding: 50px;
            text-align: center;
        }

        .container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            margin: auto;
        }

        .attractive-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #0086b3;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            border: 2px solid #0086b3;
            transition: background-color 0.3s ease;
        }

        .attractive-button:hover {
            background-color: #2980b9;
            border-color: #2980b9;
        }
        .user-list {
            list-style: none;
            padding: 0;
        }

        .user-list-item {
            margin-bottom: 10px;
            background-color: #eaeaea;
            padding: 10px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Available Users</h2>
        <h5>select to group</h5>
        <form id="group-chat-form">
            <ul class="user-list">
                {% for user in users %}
                    <li class="user-list-item">
                        <input type="checkbox" name="selected_users[]" value="{{ user.id }}" id="user{{ user.id }}">
                        <label for="user{{ user.id }}">{{ user.username }}</label>
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'home' %}"><button type="button" class="attractive-button" id="start-group-chat-btn">Start Group Chat</button></a>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelector('#start-group-chat-btn').addEventListener('click', function() {
                var selectedUserIds = [];
                var checkboxes = document.querySelectorAll('input[name="selected_users[]"]:checked');

                checkboxes.forEach(function(checkbox) {
                    selectedUserIds.push(checkbox.value);
                    checkbox.checked = false;
                });

                console.log('Before sorting:', selectedUserIds);
                selectedUserIds = selectedUserIds.slice().sort(function(a, b) {
                    return a - b;
                });
                console.log('After sorting:', selectedUserIds);

                console.log('Selected User IDs:', selectedUserIds);

                // Send an AJAX request to the server
                var xhr = new XMLHttpRequest();

                xhr.open('POST', '/'); // Replace with your actual server endpoint
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                xhr.setRequestHeader('X-CSRFToken', getCSRFToken());

                xhr.onload = function() {
                    if (xhr.status === 200) {
                        console.log('Group chat started successfully.');
                    } else {
                        console.error('Failed to start group chat.');
                    }
                };

                var data = 'selectedUserIds=' + encodeURIComponent(selectedUserIds.join(','));
                xhr.send(data);
            });
        });

        // Function to get CSRF token from cookies
        function getCSRFToken() {
            var csrfToken = null;
            document.cookie.split(';').forEach(function(cookie) {
                var parts = cookie.split('=');
                if (parts[0].trim() === 'csrftoken') {
                    csrfToken = parts[1].trim();
                }
            });
            return csrfToken;
        }
    </script>

</body>
</html>

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" />
    {% block css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}
    <script>
        function showDialog() {
            document.getElementById('dialogBox').style.display = 'block';
        }

        function closeDialog() {
            document.getElementById('dialogBox').style.display = 'none';
        }
    </script>
</body>

</html>

templates/global_chat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chat-App{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row chat-top">
            <div class="col-sm-4 border-right border-secondary">
                <img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{request.user.username}}</span>
                <span class="float-right mt-2">
                    <div class="notification">
                        <i class="fa fa-bell-o" aria-hidden="true"></i>
                        <span class="badge" id="count_badge"></span>
                    </div>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-left-fill mx-3"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                    </svg>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mr-2"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                    </svg>
                </span>


            </div>
            <div class="col-sm-8">
                <img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{receiver.username}}</span>
                {% if user.userprofilemodel.online_status %}
                <small id="{{user.username}}_small">Online</small>
                {% else %}
                <small id="{{user.username}}_small">Offline</small>
                {% endif %}
                <span class="float-right mt-2">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                    </svg>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mx-3"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                    </svg>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                {% if user.userprofilemodel.online_status %}
                                <td><a style="color: green" id="{{user.username}}_status" href="{% url 'chat' receiver_id=user.id %}">{{user.username}}</a></td>
                                {% else %}
                                <td><a style="color: grey" id="{{user.username}}_status" href="{% url 'chat' receiver_id=user.id %}">{{user.username}}</a></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                            <tr>
                                <td><a style="color: green" id="global_chat_id" href="#">Global Chats</a></td>
                            </tr>
                            <!-- end -->
                        </tbody>
                    </table>
                </div>

            </div>
            <div class="col-sm-8 message-area">
                <div class="message-table-scroll">
                    <table class="table">
                        <tbody id='chat-body'>
                            {% for message in messages_in_room %}
                            {% if message.sender == request.user %}
                            <tr>
                                <td>
                                    <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded">
                                        <small style="color: white">{{message.sender}}</small><br>
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>
                                    <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded">
                                        <small style="color: white">{{message.sender}}</small><br>
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row message-box p-3">
                    <div class="col-sm-2 mt-2">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                                d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683z" />
                            <path
                                d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip mx-2"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M15 4H1v8h14V4zM1 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H1z" />
                            <path
                                d="M13 4a2 2 0 0 0 2 2V4h-2zM3 4a2 2 0 0 1-2 2V4h2zm10 8a2 2 0 0 1 2-2v2h-2zM3 12a2 2 0 0 0-2-2v2h2zm7-4a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" />
                        </svg>
                    </div>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="message_input" placeholder="Write message...">

                    </div>
                    <div class="col-sm-2 mt-1">
                        <div class="control">
                            <button class="btn btn-success" id="chat-message-submit">Submit</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

{{receiver.id|json_script:"receiver"}}
{{user.id|json_script:"json-username"}}
{{user.username|json_script:"json-username-receiver"}}
{{request.user.username|json_script:"json-message-username"}}
{% endblock %}
{% block javascript %}
<script src="{% static 'js/global_chat.js' %}"></script>

{% endblock %}

templates/group_chat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chat-App{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}

<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row chat-top">
            <div class="col-sm-4 border-right border-secondary">
                <img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{request.user.username}}</span>
                <span class="float-right mt-2">
                    <div class="notification">
                        <i class="fa fa-bell-o" aria-hidden="true"></i>
                        <span class="badge" id="count_badge"></span>
                    </div>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-left-fill mx-3"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                    </svg>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mr-2"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                    </svg>
                </span>


            </div>
            <div class="col-sm-8">
                <img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{group_chat_room.group_name}}</span>
                {% if user.userprofilemodel.online_status %}
                <small id="{{user.username}}_small">Online</small>
                {% else %}
                <small id="{{user.username}}_small">Offline</small>
                {% endif %}
                <span class="float-right mt-2">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                    </svg>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mx-3"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                    </svg>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                {% if user.userprofilemodel.online_status %}
                                <td><a style="color: green" id="{{user.username}}_status" href="{% url 'chat' receiver_id=user.id %}">{{user.username}}</a></td>
                                {% else %}
                                <td><a style="color: grey" id="{{user.username}}_status" href="{% url 'chat' receiver_id=user.id %}">{{user.username}}</a></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                            {% for group_chat in group_list %}
                                <tr>
                                    <td><a href="{% url 'group_with_id' chat_room_id=group_chat.roomId %}">
                                        {{group_chat}}
                                    </a></td>
                                </tr>
                            {% endfor %}
                            <!-- end -->
                        </tbody>
                    </table>
                </div>

            </div>
            <div class="col-sm-8 message-area">
                <div class="message-table-scroll">
                    <table class="table">
                        <tbody id='chat-body'>
                            {% for message in messages_in_room %}
                            {% if message.sender == request.user %}
                            <tr>
                                <td>
                                    <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded">
                                        <small style="color: white">{{message.sender}}</small><br>
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>
                                    <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded">
                                        <small style="color: white">{{message.sender}}</small><br>
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row message-box p-3">
                    <div class="col-sm-2 mt-2">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                                d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683z" />
                            <path
                                d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip mx-2"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M15 4H1v8h14V4zM1 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H1z" />
                            <path
                                d="M13 4a2 2 0 0 0 2 2V4h-2zM3 4a2 2 0 0 1-2 2V4h2zm10 8a2 2 0 0 1 2-2v2h-2zM3 12a2 2 0 0 0-2-2v2h2zm7-4a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" />
                        </svg>
                    </div>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="message_input" placeholder="Write message...">

                    </div>
                    <div class="col-sm-2 mt-1">
                        <div class="control">
                            <button class="btn btn-success" id="chat-message-submit">Submit</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>
{{chat_room_id | json_script:"chat_room_id"}}
{{receiver.id|json_script:"receiver"}}
{{user.id|json_script:"json-username"}}
{{user.username|json_script:"json-username-receiver"}}
{{request.user.username|json_script:"json-message-username"}}
{% endblock %}
{% block javascript %}
{#<script src="{% static 'js/chat.js' %}"></script>#}
{# <script src="{% static 'js/global_chat.js' %}"></script>#}
{# <script src="{% static 'js/notify.js' %}"></script> #}
<script src="{% static 'js/group_chat.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chat App{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>
    .icon-button {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 30px;
        height: 30px;
        color: #333333;
        background: #dddddd;
        border: none;
        outline: none;
        border-radius: 50%;
        margin-top: 8px;
        margin-left: 23px;
    }

    .icon-button:hover {
        cursor: pointer;
    }

    .icon-button:active {
        background: #cccccc;
    }

    .icon-button__badge {
        position: absolute;
        top: -10px;
        right: -10px;
        width: 20px;
        height: 20px;
        background: red;
        color: #ffffff;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 50%;
    }

    /* Add styles for the dialog box */
    .dialog-box {
        display: none;
        position: fixed;
        top: 10%;
        left: 86%;
        transform: translate(-50%, -50%);
        padding: 20px;
        background: #fff;
        border: 1px solid #ddd;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        z-index: 1000;
    }

    /* Add styles for the close button */
    .close-button {
        position: absolute;
        top: 10px;
        right: 10px;
        cursor: pointer;
    }
</style>
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top" style="text-align: center">
            <a href="{% url 'accounts:logout' %}" style="color: rgb(255, 255, 255)">Logout</a>
            <button type="button" class="icon-button" onclick="showDialog()">
                <span class="material-icons">notifications</span>
                <span class="icon-button__badge">2</span>
            </button>

            <div class="dialog-box" id="dialogBox">
                <span class="close-button" onclick="closeDialog()">X</span>
                <p>This is your notification content.</p>
            </div>
        </div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            <a href="{% url 'add_group' %}"><button id="add-group-btn" class="attractive-button" onclick="">Add Group</button></a>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a id="registered-users-list" href="{% url 'chat' receiver_id=user.id %}">{{user.username}}</a></td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td><a style="color: green" id="global_chat_id" href="{% url 'global' %}">Global Chats</a></td>
                            </tr>
                            <!-- end -->
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}